/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.hanni.ui;

import com.hanni.dao.BaoCaoThongKeDAO;
import com.hanni.entity.BaoCaoThongKe;
import com.hanni.utils.MsgBox;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class BCTK2 extends javax.swing.JDialog {
    BaoCaoThongKeDAO dao = new BaoCaoThongKeDAO ();        
    int row = 0;
    int chonTime = 1;
    /**
     * Creates new form BCTK2
     */
    public BCTK2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fillTable();
        fillTableDoanhThu2();
        setLocationRelativeTo(null);
    }
    
    void fillTableDoanhThu2() {
        DefaultTableModel model = (DefaultTableModel) tblDoanhThu2.getModel();
        model.setRowCount(0);
        String thoiGian;
        
        try {
            List<BaoCaoThongKe> list = new ArrayList<>();
            if (chonTime == 2) {
                list = dao.selectAllDoanhThuThang();
            } else if (chonTime == 3) {
                list = dao.selectAllDoanhThuNam();
            } else if (chonTime == 1) {
                list = dao.selectAllDoanhThuNgay();
            }
            
            for(BaoCaoThongKe bctk : list) {
                Object[] row = {
                    bctk.getTenSanPham(),
                    bctk.getSoLuong(),
                    bctk.getDoanhThu()                   
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            System.out.println(""+e);
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu2!");
        }
    }
    
//    void fillTableDoanhThu() {
//        DefaultTableModel model = (DefaultTableModel) tblDoanhThu.getModel();
//        model.setRowCount(0);
//        String thoiGian;
//        
//        try {
//            //List<BaoCaoThongKe> list = dao.selectById(txtNgay.getText());
//            List<BaoCaoThongKe> kh = (List<BaoCaoThongKe>) dao.selectById(txtNam.getText());
//            for(BaoCaoThongKe bctk : kh) {
//                Object[] row = {
//                    bctk.getMaDH(),
//                    bctk.getNgayLap(),
//                    bctk.gettenKhachHang(),
//                    bctk.getTongTien(),
//                    bctk.getTenSanPham(),
//                    bctk.getDonGia(),
//                    bctk.getSoLuong()
//                };
//                model.addRow(row);
//            }
//        } catch (Exception e) {
//            System.out.println(""+e);
//            MsgBox.alert(this, "Lỗi truy vấn dữ liệu1!");
//        }
//    }
    //-------------------------------------------------------------------------------------------------------------------
    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblThongKe.getModel();
        model.setRowCount(0);
        
        try {
            List<BaoCaoThongKe> list = dao.selectAll();
            for(BaoCaoThongKe bctk : list) {
                String trangT;
                if (bctk.getTrangThai() == true) {
                    trangT = "Đã Thanh Toán";
                } else {
                    trangT = "Chưa Được Thanh Toán";
                }
                Object[] row = {
                    bctk.getMaDH(),
                    bctk.getNgayLap(),
                    bctk.gettenKhachHang(),
                    bctk.getTongTien(),
                    trangT,
                    bctk.getTenSanPham(),
                    bctk.getDonGia(),
                    bctk.getSoLuong()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jColorChooser1 = new javax.swing.JColorChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongKe = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDoanhThu2 = new javax.swing.JTable();
        btnDoanhThuNgay = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Báo Cáo Thống Kê");

        jTabbedPane1.setToolTipText("");

        tblThongKe.setBackground(new java.awt.Color(255, 250, 243));
        tblThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Đơn Hàng", "Ngày Lập", "Tên Khách Hàng", "Tổng Tiền", "Trạng Thái", "Tên Sản Phẩm", "Đơn Giá", "Số Lượng"
            }
        ));
        tblThongKe.setSelectionBackground(new java.awt.Color(0, 102, 255));
        jScrollPane1.setViewportView(tblThongKe);

        jTabbedPane1.addTab("bảng Thống Kê Đơn hàng", jScrollPane1);

        jPanel4.setBackground(new java.awt.Color(255, 241, 236));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 255));
        jButton1.setText("Doanh Thu SP Trong Tháng Này");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 255));
        jButton3.setText("Doanh Thu SP Trong Năm Nay");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jScrollPane4.setBackground(new java.awt.Color(255, 250, 243));
        jScrollPane4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblDoanhThu2.setBackground(new java.awt.Color(255, 250, 243));
        tblDoanhThu2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên Sản Phẩm", "Số Lượng", "Doanh Thu"
            }
        ));
        tblDoanhThu2.setSelectionBackground(new java.awt.Color(0, 102, 255));
        jScrollPane4.setViewportView(tblDoanhThu2);

        btnDoanhThuNgay.setBackground(new java.awt.Color(255, 255, 204));
        btnDoanhThuNgay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDoanhThuNgay.setForeground(new java.awt.Color(0, 102, 255));
        btnDoanhThuNgay.setText("Doanh Thu SP Trong Hôm Nay");
        btnDoanhThuNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoanhThuNgayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnDoanhThuNgay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(40, 40, 40)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(btnDoanhThuNgay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Doanh thu sản phẩm", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoanhThuNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoanhThuNgayActionPerformed
        // TODO add your handling code here:
        chonTime = 1;
        fillTableDoanhThu2();
    }//GEN-LAST:event_btnDoanhThuNgayActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        chonTime = 3;
        fillTableDoanhThu2();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        chonTime = 2;
        fillTableDoanhThu2();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BCTK2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BCTK2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BCTK2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BCTK2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BCTK2 dialog = new BCTK2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoanhThuNgay;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblDoanhThu2;
    private javax.swing.JTable tblThongKe;
    // End of variables declaration//GEN-END:variables
}
